data_path: 'data/input/incidence_strains_spb_2_age_groups.csv'
contact_matrix_path: 'data/input/contact_matrix_2_age_groups.p'

city: 'Saint Petersburg'
year: 2013
percent_protected: 0.2
sigma: 2.5

INCIDENCE_TYPE: 'total'
DATA_DETAIL: True
MODEL_DETAIL: True
A_DETAIL: False
PREDICT: False

#age_groups: ['0-2', '3-6', '7-14', '15 и ст.']
age_groups: ['0-14', '15 и ст.']
strains: ['A(H1N1)pdm09', 'A(H3N2)', 'B']

output_folder: 'output'
cache_folder: 'output/cache_fit'

SAVE_PRESET: True
